chore: revert the previous commit
[It turns out](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runsusing-for-docker-container-actions)
that the `runs.using` field for Docker container actions must be set to
the value `docker` and the `runs.image` field
[will not accept variable inputs](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runsimage).
Indeed, trying to run this action with a variable input results in an
error:

```
Download action repository 'phylum-dev/phylum-analyze-pr-action@select_image' (SHA:f8df0ed378abcfadaae57f7a015bc101bd3e608b)
Error: phylum-dev/phylum-analyze-pr-action/select_image/action.yml (Line: 34, Col: 10): Unrecognized named-value: 'inputs'. Located at position 1 within expression: inputs.image
Error: Fail to load phylum-dev/phylum-analyze-pr-action/select_image/action.yml
```

The solution going forward is to recommend using container jobs/steps to
specify a different image/tag. This will be a documentation-only update.